[package]
authors = ["Tangram <root@tangram.dev"]
description = "Tangram makes it easy for programmers to train, deploy, and monitor machine learning models."
documentation = "https://docs.rs/tangram"
edition = "2018"
homepage = "https://github.com/tangramdotdev/tangram"
license = "MIT"
name = "tangram_metrics"
publish = true
repository = "https://github.com/tangramdotdev/tangram"
version = "0.7.0"

[lib]
path = "lib.rs"

[dev-dependencies]
insta = "1"

[dependencies]
itertools = "0.10"
ndarray = { version = "0.15", features = ["rayon"] }
num = "0.4"
tangram_zip = { version = "0.7.0", path = "../zip" }
