cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_example_advanced"

edition = { workspace = true }
license = { workspace = true }
publish = false
version = { workspace = true }

[[bin]]
name = "modelfox_example_advanced"
path = "main.rs"

[dependencies]
anyhow = { workspace = true }
modelfox = { workspace = true }
