[package]
edition = "2021"
rust-version = "1.56"
license = "MIT"
name = "tangram_license"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[[bin]]
name = "tangram_license"
path = "main.rs"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
base64 = "0.13"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "3.0.0-rc.9", features = ["derive", "env"] }
duct = "0.13"
indoc = "1"
pem = "1"
rand = "0.8"
rsa = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tangram_id = { path = "../id" }
