[package]
edition = "2021"
rust-version = "1.56"
name = "tangram_app_ui"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = { version = "0.6", features = ["serde"] }
pinwheel = "0.2"
serde = { version = "1", features = ["derive"] }
tangram_ui = { path = "../../ui" }
