[package]
edition = "2021"
rust-version = "1.56"
name = "tangram_dev"
publish = false
version = "0.0.0"

[[bin]]
name = "tangram_dev"
path = "main.rs"

[dependencies]
clap = { version = "=3.0.0-beta.5", features = ["color"] }
sunfish = "0.3"
tokio = { version = "1", features = ["full"] }
