[package]
edition = "2021"
rust-version = "1.56"
name = "tangram_www_docs_getting_started_predict_javascript_server"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
pinwheel = "0.2"
sunfish = "0.2"
tangram_ui = { path = "../../../../../../../ui" }
tangram_www_layouts = { path = "../../../../../../layouts" }
tangram_www_ui = { path = "../../../../../../ui" }
