[package]
edition = "2018"
name = "tangram_www_benchmarks_client"
publish = false
version = "0.0.0"

[[bin]]
name = "tangram_www_benchmarks_client"
path = "main.rs"

[dependencies]
console_error_panic_hook = "0.1"
pinwheel = "0.2"
tangram_charts = { path = "../../../../charts" }
tangram_ui = { path = "../../../../ui" }
tangram_www_benchmarks_common = { path = "../common" }
web-sys = "0.3"
