[package]
edition = "2021"
rust-version = "1.56"
name = "tangram_app_common"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dev-dependencies]
insta = "1"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = { version = "0.6", features = ["serde"] }
fnv = "1"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
indexmap = { version = "1.6", features = ["serde-1"] }
itertools = "0.10"
lettre = { version = "0.10.0-rc.2", default-features = false, features = ["builder", "hostname", "smtp-transport", "tokio1-rustls-tls"] }
memmap = "0.7"
ndarray = { version = "0.15", features = ["rayon"] }
num = "0.4"
pinwheel = "0.2"
rand = "0.8"
rust-s3 = { version = "0.28" , default-features = false, features = ["tokio-rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.5", default-features = false, features = ["any", "chrono", "postgres", "runtime-tokio-rustls", "sqlite"] }
sunfish = "0.3"
tangram_app_ui = { path = "../../app/ui" }
tangram_charts = { path = "../../charts" }
tangram_core = { path = "../../core" }
tangram_finite = { path = "../../finite" }
tangram_id = { path = "../../id" }
tangram_model = { path = "../../model" }
tangram_text = { path = "../../text" }
tangram_ui = { path = "../../ui" }
tangram_zip = { path = "../../zip" }
time = "0.3"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
url = { version = "2", features = ["serde"] }
