[package]
edition = "2021"
rust-version = "1.56"
name = "tangram_app_model_index_client"
publish = false
version = "0.0.0"

[[bin]]
name = "tangram_app_model_index_client"
path = "main.rs"

[dependencies]
console_error_panic_hook = "0.1"
pinwheel = "0.2"
tangram_charts = { path = "../../../../../../../../charts" }
tangram_ui = { path = "../../../../../../../../ui" }
wasm-bindgen = "0.2"
