[package]
edition = "2021"
rust-version = "1.56"
name = "tangram_www_layouts"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
pinwheel = "0.2"
sunfish = "0.2"
tangram_ui = { path = "../../ui" }
tangram_www_content = { path = "../content" }
tangram_www_ui = { path = "../ui" }
