[package]
edition = "2018"
name = "tangram_www_docs_getting_started_inspect_server"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
num = "0.4"
pinwheel = "0.2"
sunfish = "0.2"
tangram_ui = { path = "../../../../../../ui" }
tangram_www_docs_inspect_common = { path = "../common" }
tangram_www_layouts = { path = "../../../../../layouts" }
tangram_www_ui = { path = "../../../../../ui" }
