[package]
edition = "2018"
name = "tangram_app_repo_index_server"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = { version = "0.5", features = ["serde"] }
futures = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
pinwheel = "0.1"
serde = { version = "1", features = ["derive"] }
serde_urlencoded = "0.7"
sqlx = { version = "0.5", default-features = false, features = ["any", "chrono", "postgres", "runtime-tokio-rustls", "sqlite"] }
sunfish = { path = "../../../../../../sunfish" }
tangram_app_common = { path = "../../../../../common" }
tangram_app_layouts = { path = "../../../../../layouts" }
tangram_app_ui = { path = "../../../../../ui" }
tangram_error = { path = "../../../../../../error" }
tangram_id = { path = "../../../../../../id" }
tangram_model = { path = "../../../../../../model" }
tangram_ui = { path = "../../../../../../ui" }
