[package]
edition = "2021"
rust-version = "1.56"
name = "tangram_app_tuning_client"
publish = false
version = "0.0.0"

[[bin]]
name = "tangram_app_tuning_client"
path = "main.rs"

[dependencies]
pinwheel = "0.2"
tangram_app_tuning_common = { path = "../common" }
tangram_ui = { path = "../../../../../../../../ui" }
web-sys = "0.3"
