[package]
edition = "2021"
name = "tangram_app_new_member_server"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
futures = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
lettre = { version = "0.10.0-rc.2", default-features = false, features = ["builder", "hostname", "smtp-transport", "tokio1-rustls-tls"] }
pinwheel = "0.2"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_urlencoded = "0.7"
sqlx = { version = "0.5", default-features = false, features = ["any", "chrono", "postgres", "runtime-tokio-rustls", "sqlite"] }
sunfish = "0.6"
tangram_app_context = { path = "../../../../../../context" }
tangram_app_core = { path = "../../../../../../core" }
tangram_app_layouts = { path = "../../../../../../layouts" }
tangram_id = { path = "../../../../../../../id" }
tangram_ui = { path = "../../../../../../../ui" }
tokio = { version = "1", features = ["full"] }
url = { version = "2", features = ["serde"] }
