[package]
edition = "2018"
name = "tangram_www_index_common"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
tangram_ui = { path = "../../../../ui" }
num = "0.4"
pinwheel = "0.2"
serde = { version = "1", features = ["derive"] }
wasm-bindgen = "0.2"
web-sys = "0.3"
