cargo-features = ["workspace-inheritance"]

[package]
name = "modelfox_example_basic"

edition = { workspace = true }
license = { workspace = true }
publish = false
version = { workspace = true }

[[bin]]
name = "modelfox_example_basic"
path = "main.rs"

[dependencies]
modelfox = { workspace = true }
