[package]
edition = "2018"
name = "tangram_app_training_metrics_precision_recall_server"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
futures = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
num = "0.4"
pinwheel = "0.2"
sunfish = "0.2"
tangram_app_common = { path = "../../../../../../../../common" }
tangram_app_layouts = { path = "../../../../../../../../layouts" }
tangram_charts = { path = "../../../../../../../../../charts" }
tangram_core = { path = "../../../../../../../../../core" }
tangram_finite = { path = "../../../../../../../../../finite" }
tangram_id = { path = "../../../../../../../../../id" }
tangram_model = { path = "../../../../../../../../../model" }
tangram_ui = { path = "../../../../../../../../../ui" }
